### ISSUE TITLE
What is the effect of high simlayer-threshold

### ISSUE THREAD

**Issue by 51364x** [yqrashawn/GokuRakuJoudo#213]
here is my profile, i feel not soomthness when using simlayer, so I adjust some varialbles, after incresase the simlayer threshold, simlayers become easier to press, but seems no drawback, my simlayer active key is `spacebar`.
```
  :profiles 
    {:Default 
      {:default true
      :sim     50
      :simlayer-threshold 10000
      :dlay   500
      :alone   500
      :held    1000}}
```

**Comment by yqrashawn** [comment]
Hi, it's `simultaneous_threshold_milliseconds` in karabiner. Doc at https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/simultaneous-options/
High threshold means more likely to count, e.g., `spacebar+a` as `space` and `a` pressed at the same time instead of `spacebar` then `a`
